#!/bin/sh
JOB_DIR=%%JOB_DIR%%
TAG=%%TAG%%
ARTIFACT_REPOSITORY_DIR=%%ARTIFACT_REPOSITORY_DIR%%
INITIAL_STATE=task
RESOURCES_GOBYWEB_SERVER_SIDE_FILESETS_JAR="filesets.jar"
RESOURCES_GOBYWEB_SERVER_SIDE_DEPENDENCIES_JAR="serverside-dependencies.jar"
FILESET_COMMAND="java -cp ${RESOURCES_GOBYWEB_SERVER_SIDE_FILESETS_JAR}:${RESOURCES_GOBYWEB_SERVER_SIDE_DEPENDENCIES_JAR} org.campagnelab.gobyweb.filesets.JobInterface --job-tag %%TAG%%"
GOBY_DIR=${JOB_DIR}

set -x
