#!/bin/sh
PB_FILE="pbfile.pb"
JOB_DIR=%%JOB_DIR%%
TAG=%%TAG%%
INITIAL_STATE=task
RESOURCES_GOBYWEB_SERVER_SIDE_FILESETS_JAR="filesets.jar"
RESOURCES_GOBYWEB_SERVER_SIDE_DEPENDENCIES_JAR="serverside-dependencies.jar"
FILESET_COMMAND="java -cp ${RESOURCES_GOBYWEB_SERVER_SIDE_FILESETS_JAR}:${RESOURCES_GOBYWEB_SERVER_SIDE_DEPENDENCIES_JAR} org.campagnelab.gobyweb.filesets.FileSetManager --task-tag %%TAG%%"
