#!/bin/sh
JOB_DIR=%%JOB_DIR%%
TMPDIR=`pwd`
TAG=%%TAG%%
ARTIFACT_REPOSITORY_DIR=%%ARTIFACT_REPOSITORY_DIR%%
INITIAL_STATE=task
PLUGIN_ID=%%PLUGIN_ID%%
PLUGIN_VERSION=%%PLUGIN_VERSION%%
RESOURCES_GOBYWEB_SERVER_SIDE_FILESETS_JAR="filesets.jar"
RESOURCES_GOBYWEB_SERVER_SIDE_DEPENDENCIES_JAR="serverside-dependencies.jar"
FILESET_COMMAND="java -cp ${RESOURCES_GOBYWEB_SERVER_SIDE_FILESETS_JAR}:${RESOURCES_GOBYWEB_SERVER_SIDE_DEPENDENCIES_JAR} org.campagnelab.gobyweb.filesets.JobInterface --fileset-area-cache ${TMPDIR} --job-tag %%TAG%%"
GOBY_DIR=${JOB_DIR}
GOBYWEB_CONTAINER_TECHNOLOGY=%%GOBYWEB_CONTAINER_TECHNOLOGY%%
GOBYWEB_CONTAINER_NAME=%%GOBYWEB_CONTAINER_NAME%%
OGE_WRAPPERS_PATHS=%%OGE_WRAPPER_PATHS%%
export SGE_O_WORKDIR=${JOB_DIR}
